/**
 * Curated lucide-react icon re-exports.
 * All named exports have the same prop shape as lucide-react's LucideIcon.
 */
import type { LucideIcon } from 'lucide-react'

export const IconChevronDown: LucideIcon
export const IconChevronRight: LucideIcon
export const IconChevronLeft: LucideIcon
export const IconChevronUp: LucideIcon
export const IconArrowLeft: LucideIcon
export const IconArrowRight: LucideIcon
export const IconMenu: LucideIcon
export const IconX: LucideIcon
export const IconSearch: LucideIcon
export const IconFilter: LucideIcon
export const IconSliders: LucideIcon
export const IconMore: LucideIcon
export const IconExternalLink: LucideIcon
export const IconDownload: LucideIcon
export const IconUpload: LucideIcon
export const IconCopy: LucideIcon
export const IconPlus: LucideIcon
export const IconTrash: LucideIcon
export const IconEdit: LucideIcon
export const IconSave: LucideIcon
export const IconRefresh: LucideIcon
export const IconPlay: LucideIcon
export const IconPause: LucideIcon
export const IconToggleOff: LucideIcon
export const IconToggleOn: LucideIcon
export const IconSend: LucideIcon
export const IconZap: LucideIcon
export const IconCheckCircle: LucideIcon
export const IconAlertTriangle: LucideIcon
export const IconAlertCircle: LucideIcon
export const IconInfo: LucideIcon
export const IconClock: LucideIcon
export const IconLoader: LucideIcon
export const IconBan: LucideIcon
export const IconShield: LucideIcon
export const IconShieldAlert: LucideIcon
export const IconShieldCheck: LucideIcon
export const IconBug: LucideIcon
export const IconLock: LucideIcon
export const IconUnlock: LucideIcon
export const IconEye: LucideIcon
export const IconEyeOff: LucideIcon
export const IconFingerprint: LucideIcon
export const IconScan: LucideIcon
export const IconBarChart: LucideIcon
export const IconTrendingUp: LucideIcon
export const IconTrendingDown: LucideIcon
export const IconFileText: LucideIcon
export const IconFolder: LucideIcon
export const IconDatabase: LucideIcon
export const IconTag: LucideIcon
export const IconTags: LucideIcon
export const IconHash: LucideIcon
export const IconGlobe: LucideIcon
export const IconServer: LucideIcon
export const IconNetwork: LucideIcon
export const IconWorkflow: LucideIcon
export const IconGitBranch: LucideIcon
export const IconUser: LucideIcon
export const IconUsers: LucideIcon
export const IconUserPlus: LucideIcon
export const IconMail: LucideIcon
export const IconMessage: LucideIcon
export const IconBell: LucideIcon
export const IconCalendar: LucideIcon
export const IconBuilding: LucideIcon
export const IconSettings: LucideIcon
export const IconHelp: LucideIcon
export const IconStar: LucideIcon
export const IconBookmark: LucideIcon
export const IconLink: LucideIcon
export const IconTarget: LucideIcon
export const IconCrosshair: LucideIcon
export const IconBot: LucideIcon
export const IconSparkles: LucideIcon
